rent/urls.py
from django.conf.urls import url
from rent import views
from django.urls import path

app_name = 'rent'

urlpatterns = [
    path('', views.rent_request,name='rent_request'),
    path('pause', views.rent_pause,name='rent_pause'),
    path('pause', views.rent_finish,name='rent_finish'),

]

smartx/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from signup import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^setup/', include('vehicles.urls')),
    url(r'^login/$',views.user_login, name='user_login'),
    url(r'^logout/$',views.user_logout , name='logout'),
    url(r'^rent/', include('rent.urls')),



]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

rent/models.py
from django.db import models

# Create your models here.

rent/forms.py
from django import forms
from vehicles.models import Vehicle

class FormModelRent(forms.ModelForm):
    class Meta():

        model = Vehicle
        fields = ['code']

rent/views.py
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.urls import reverse
from django.views import View
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from vehicles.models import Vehicle
from rent import views
from signup.forms import UserForm
from rent import forms
from django.shortcuts import render



# Create your views here.


@login_required
def rent_request(request):
    form_rent = forms.FormModelRent()
    if request.method == 'POST' and form_rent.is_valid:
        form_rent = forms.FormModelRent(request.POST)
        bike_code = request.POST["code"]

        bike = Vehicle.objects.all().filter(code=bike_code)
        my_bike_status = bike.status

        if bike.status == 'r':
            bike.status = 's'
            bike.save()

        return render(request,'signup/dashboard.html',
                    context={"bike":bike_code,"status":my_bike_status,'time':'now' })


    else:
        print('ERROR')

    return render(request,'rent/rent_vehicle.html',{'form_rent': form_rent})


@login_required
def rent_pause(request):
    if my_bike.status == 's':
        my_bike.status = 'b'
        my_bike.save()


@login_required
def rent_finish(request):
    pass

rent/templates/rent/rent_continue.html
{% extends 'signup/base.html' %}

{% block content %}
  <h2>you ar usin your bike</h2>
  <h3>To finish using this bike  please click this link</h3>

  <a href="{% url 'rent:rent_finish'%}"></a>
{% endblock %}

rent/templates/rent/rent_pause.html
{% extends 'signup/base.html' %}

{% block content %}
  <h2>You paused the bz</h2>
  <h3>for continue your service please click this link</h3>

  <a href="{% url 'rent:rent_continue'%}"></a>
{% end block %}

rent/templates/rent/rent_vehicle.html
{% extends 'signup/base.html'%}

{% block content %}
{% if user.is_active %}

    <form method="post" name="code">
      {{form_rent.as_p }}
      {% csrf_token %}

      <input type="submit" class="btn btn-primary" value="Rent">

    </form>

    {% else %}
    <h3>You have to log in to rent a vehicle</h3>
    <a href="{% url 'login' %}"> Log In</a>
    {% endif %}
{% endblock %}