rent/urls.py
from django.conf.urls import url
from rent import views
from django.urls import path

app_name = 'rent'

urlpatterns = [
    path('', views.rent_request,name='rent_request'),
    path('pause', views.rent_pause,name='rent_pause'),
    path('pause', views.rent_finish,name='rent_finish'),

]

signup/urls.py
from django.conf.urls import url
from signup import views
from django.urls import path

app_name = 'signup'

urlpatterns = [
    url(r'^$', views.VehicleListView.as_view(),name='list'),
    # url(r'^(?P<pk>[-\w]+)/$'), views.DeviceDetailView.as_view())
    path('<int:pk>',views.VehicleDetailView.as_view()),
    url(r'^vehicle/$',views.form_vehicle_view,name='form_vehicle'),
    url(r'^master/$',views.form_master_view,name='form_master'),
    path('signup',views.signup,name='registered'),


]

smartx/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from signup import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^setup/', include('vehicles.urls')),
    url(r'^login/$',views.user_login, name='user_login'),
    url(r'^logout/$',views.user_logout , name='logout'),
    url(r'^rent/', include('rent.urls')),



]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/',include(debug_toolbar.urls))
    ] + urlpatterns

vehicles/urls.py
from django.conf.urls import url
from vehicles import views
from django.urls import path

app_name = 'vehicles'

urlpatterns = [
    url(r'^$', views.VehicleListView.as_view(),name='list'),
    path('<int:pk>',views.VehicleDetailView.as_view()),
    url(r'^vehicle/$',views.form_vehicle_view,name='form_vehicle'),
    url(r'^master/$',views.form_master_view,name='form_master'),

]

signup/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=None)

    portfolio_site = models.URLField(blank= True)
    profile_pics = models.ImageField(upload_to= 'profile_pics',blank=True)

    def __str__(self):
        return self.user.username

signup/forms.py
from django import forms
from django.contrib.auth.models import User
from signup.models import UserProfileInfo
from vehicles.models import Vehicle,Master
# from captcha.fields import ReCaptchaField
# from captcha.widgets import ReCaptchaV2Invisible


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

#     captcha = ReCaptchaField(
#     public_key='6Ldou_0UAAAAANymj1RdQ7VqZy97FLslCAI02aCU',
#     private_key='6Ldou_0UAAAAAAFPVYs7nl3FEL5op63LtTm-W3y_',
# )
#     captcha = ReCaptchaField(widget=ReCaptchaV2Invisible)

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pics')

signup/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,ListView,DetailView
from django.utils import timezone
from signup import forms
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect , HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request,'signup/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def signup(request):
    registered = False
    if request.method == 'POST':
        user_form = forms.UserForm(data=request.POST)
        profile_form = forms.UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

        elif 'profile_pics' in request.FILES:
            profile.profile_pics = request.FILES.get('profile_pics')

            profile.save()

            registered = True
        else:

            print(user_form.errors,profile_form.errors)

    else:
        user_form = forms.UserForm()
        profile_form = forms.UserProfileInfoForm()

        return render(request, 'signup/registration.html',context={'user_form':user_form,'profile_form':profile_form,'registered':registered})



# LOGIN
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'),{'user':username})
            else:
                HttpResponse("account not active")

        else:
            print("someone tried to login but failed")
            print("username : {} , password : {} ".format(username,password))
            return HttpResponse("invalid login details supplied")

    else:
        return render(request,'signup/login.html')

templates/signup/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Register</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container">

      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'index'%}">HOME</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        {% if user.is_superuser %}
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'vehicles:form_master'%}">Master <span class="sr-only"></span></a>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{% url 'vehicles:form_vehicle'%}">Vehicles <span class="sr-only"></span></a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'vehicles:list'%}">List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="{% url 'index' %}">Register</a>
        </li>
      </ul>
      {% if user.is_authenticated %}
      <form class="form-inline my-2 my-lg-0" action="{% url 'logout' %}">
        <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"> -->
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"> Log Out</button>
      </form>
      {% else %}
      <form class="form-inline my-2 my-lg-0" action="{% url 'user_login' %}">
        <!-- <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"> -->
        <button class="btn btn-outline-danger my-2 my-sm-0" type="submit">Log In</button>
      </form>


      {% endif %}
    </div>
  </nav>

<div class="container">


    {% block content %}

    {% endblock %}
  </div>

  </body>
</html>

templates/signup/index.html
{% extends 'signup/base.html' %}

{% block content %}
<h1>Welcom to SmartX </h1>
{% if user.is_active %}

<p>{{ user }}</p>

<a href="{% url 'rent:rent_request'%}">rent</a>
{% endif %}
{% endblock %}

templates/signup/login.html
<!DOCTYPE html>

{% extends 'signup/base.html' %}

{% block content %}

<div class="jumbotron">
  <h1>please login here</h1>
  <form action="{% url 'user_login'%}" method="post">
    {% csrf_token %}
    <label for="username">Username: </label>
    <input type="text" name="username" placeholder="enter your username">

    <label for="password">Password: </label>
    <input type="password" name="password" >

    <input type="submit" name="" value="Login">

  </form>

</div>

{% endblock %}